using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace HellRoad
{
    public enum PartsID
    {
        None                = 0,
        Skull_Head          = 1,
        Skeleton_Body       = 2,
        Skeleton_Arms       = 3,
        Skeleton_Legs       = 4,
        JK_Head             = 5,
        JK_Body             = 6,
        JK_Arms             = 7,
        JK_Legs             = 8,
        GoldenMan_Head      = 9,
        GoldenMan_Body      = 10,
        GoldenMan_Arms      = 11,
        GoldenMan_Legs      = 12,
        Oni_Head            = 13,
        Oni_Body            = 14,
        Oni_Arms            = 15,
        Oni_Legs            = 16,
        OfficeWorker_Head   = 17,
        OfficeWorker_Body   = 18,
        OfficeWorker_Arms   = 19,
        OfficeWorker_Legs   = 20,
        BlueOni_Head        = 21,
        BlueOni_Body        = 22,
        BlueOni_Arms        = 23,
        BlueOni_Legs        = 24,
        Succubus_Head       = 25,
        Succubus_Body       = 26,
        Succubus_Arms       = 27,
        Succubus_Legs       = 28,
        Rabbit_Head         = 29,
        Rabbit_Body         = 30,
        Rabbit_Arms         = 31,
        Rabbit_Legs         = 32,
        Angel_Head          = 33,
        Angel_Body          = 34,
        Angel_Arms          = 35,
        Angel_Legs          = 36,
        KaminariSama_Head   = 37,
        KaminariSama_Body   = 38,
        KaminariSama_Arms   = 39,
        KaminariSama_Legs   = 40,
        Pigeon_Head         = 41,
        Pigeon_Body         = 42,
        Pigeon_Arms         = 43,
        Pigeon_Legs         = 44,
        Horse_Head          = 45,
        Horse_Body          = 46,
        Horse_Arms          = 47,
        Horse_Legs          = 48,
        Magician_Head       = 49,
        Magician_Body       = 50,
        Magician_Arms       = 51,
        Magician_Legs       = 52,
        Crab_Head           = 53,
        Crab_Body           = 54,
        Crab_Arms           = 55,
        Crab_Legs           = 56,
        Giraffe_Head        = 57,
        Giraffe_Body        = 58,
        Giraffe_Arms        = 59,
        Giraffe_Legs        = 60,
        SnowMan_Head        = 61,
        SnowMan_Body        = 62,
        SnowMan_Arms        = 63,
        SnowMan_Legs        = 64,
        Alien_Head          = 65,
        Alien_Body          = 66,
        Alien_Arms          = 67,
        Alien_Legs          = 68,
        Police_Head         = 69,
        Police_Body         = 70,
        Police_Arms         = 71,
        Police_Legs         = 72,
        Zombie_Head         = 73,
        Zombie_Body         = 74,
        Zombie_Arms         = 75,
        Zombie_Legs         = 76,
        Death_Head          = 77,
        Death_Body          = 78,
        Death_Arms          = 79,
        Death_Legs          = 80,
        YukiOnna_Head       = 81,
        YukiOnna_Body       = 82,
        YukiOnna_Arms       = 83,
        YukiOnna_Legs       = 84,
        Enma_Head           = 85,
        Enma_Body           = 86,
        Enma_Arms           = 87,
        Enma_Legs           = 88,
        KARAGE_Head         = 100,
    }

    static class PartsEnumExtension
    {
        static readonly ReadOnlyDictionary<PartsID, PartsType> dict = new ReadOnlyDictionary<PartsID, PartsType>(new Dictionary<PartsID, PartsType>()
        {
            { PartsID.None,             PartsType.Head },
            { PartsID.Skull_Head,       PartsType.Head },
            { PartsID.Skeleton_Body,    PartsType.Body },
            { PartsID.Skeleton_Arms,    PartsType.Arms },
            { PartsID.Skeleton_Legs,    PartsType.Legs },
            { PartsID.JK_Head,          PartsType.Head },
            { PartsID.JK_Body,          PartsType.Body },
            { PartsID.JK_Arms,          PartsType.Arms },
            { PartsID.JK_Legs,          PartsType.Legs },
            { PartsID.GoldenMan_Head,   PartsType.Head },
            { PartsID.GoldenMan_Body,   PartsType.Body },
            { PartsID.GoldenMan_Arms,   PartsType.Arms },
            { PartsID.GoldenMan_Legs,   PartsType.Legs },
            { PartsID.OfficeWorker_Head,   PartsType.Head },
            { PartsID.OfficeWorker_Body,   PartsType.Body },
            { PartsID.OfficeWorker_Arms,   PartsType.Arms },
            { PartsID.OfficeWorker_Legs,   PartsType.Legs },
            { PartsID.Oni_Head,         PartsType.Head },
            { PartsID.Oni_Body,         PartsType.Body },
            { PartsID.Oni_Arms,         PartsType.Arms },
            { PartsID.Oni_Legs,         PartsType.Legs },
            { PartsID.BlueOni_Head,     PartsType.Head },
            { PartsID.BlueOni_Body,     PartsType.Body },
            { PartsID.BlueOni_Arms,     PartsType.Arms },
            { PartsID.BlueOni_Legs,     PartsType.Legs },
            { PartsID.Succubus_Head,    PartsType.Head },
            { PartsID.Succubus_Body,    PartsType.Body },
            { PartsID.Succubus_Arms,    PartsType.Arms },
            { PartsID.Succubus_Legs,    PartsType.Legs },
            { PartsID.Rabbit_Head,      PartsType.Head },
            { PartsID.Rabbit_Body,      PartsType.Body },
            { PartsID.Rabbit_Arms,      PartsType.Arms },
            { PartsID.Rabbit_Legs,      PartsType.Legs },
            { PartsID.Angel_Head,       PartsType.Head },
            { PartsID.Angel_Body,       PartsType.Body },
            { PartsID.Angel_Arms,       PartsType.Arms },
            { PartsID.Angel_Legs,       PartsType.Legs },
            { PartsID.KaminariSama_Head,PartsType.Head },
            { PartsID.KaminariSama_Body,PartsType.Body },
            { PartsID.KaminariSama_Arms,PartsType.Arms },
            { PartsID.KaminariSama_Legs,PartsType.Legs },
            { PartsID.Pigeon_Head,      PartsType.Head },
            { PartsID.Pigeon_Body,      PartsType.Body },
            { PartsID.Pigeon_Arms,      PartsType.Arms },
            { PartsID.Pigeon_Legs,      PartsType.Legs },
            { PartsID.Horse_Head,       PartsType.Head },
            { PartsID.Horse_Body,       PartsType.Body },
            { PartsID.Horse_Arms,       PartsType.Arms },
            { PartsID.Horse_Legs,       PartsType.Legs },
            { PartsID.Magician_Head,    PartsType.Head },
            { PartsID.Magician_Body,    PartsType.Body },
            { PartsID.Magician_Arms,    PartsType.Arms },
            { PartsID.Magician_Legs,    PartsType.Legs },
            { PartsID.Crab_Head,        PartsType.Head },
            { PartsID.Crab_Body,        PartsType.Body },
            { PartsID.Crab_Arms,        PartsType.Arms },
            { PartsID.Crab_Legs,        PartsType.Legs },
            { PartsID.SnowMan_Head,     PartsType.Head },
            { PartsID.SnowMan_Body,     PartsType.Body },
            { PartsID.SnowMan_Arms,     PartsType.Arms },
            { PartsID.SnowMan_Legs,     PartsType.Legs },
            { PartsID.Alien_Head,       PartsType.Head },
            { PartsID.Alien_Body,       PartsType.Body },
            { PartsID.Alien_Arms,       PartsType.Arms },
            { PartsID.Alien_Legs,       PartsType.Legs },
            { PartsID.Giraffe_Head,     PartsType.Head },
            { PartsID.Giraffe_Body,     PartsType.Body },
            { PartsID.Giraffe_Arms,     PartsType.Arms },
            { PartsID.Giraffe_Legs,     PartsType.Legs },
            { PartsID.Police_Head,      PartsType.Head },
            { PartsID.Police_Body,      PartsType.Body },
            { PartsID.Police_Arms,      PartsType.Arms },
            { PartsID.Police_Legs,      PartsType.Legs },
            { PartsID.Zombie_Head,      PartsType.Head },
            { PartsID.Zombie_Body,      PartsType.Body },
            { PartsID.Zombie_Arms,      PartsType.Arms },
            { PartsID.Zombie_Legs,      PartsType.Legs },
            { PartsID.Death_Head,       PartsType.Head },
            { PartsID.Death_Body,       PartsType.Body },
            { PartsID.Death_Arms,       PartsType.Arms },
            { PartsID.Death_Legs,       PartsType.Legs },
            { PartsID.YukiOnna_Head,    PartsType.Head },
            { PartsID.YukiOnna_Body,    PartsType.Body },
            { PartsID.YukiOnna_Arms,    PartsType.Arms },
            { PartsID.YukiOnna_Legs,    PartsType.Legs },
            { PartsID.Enma_Head,        PartsType.Head },
            { PartsID.Enma_Body,        PartsType.Body },
            { PartsID.Enma_Arms,        PartsType.Arms },
            { PartsID.Enma_Legs,        PartsType.Legs },
            { PartsID.KARAGE_Head,      PartsType.Head },
        });

        public static PartsType ToPartsType(this PartsID partsEnum)
        {
            return dict[partsEnum];
        }
    }
}